### ISSUE TITLE
Modern.js Roadmap

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/modern.js#4741]
### What problem does this feature solve?

# 2023

## 2023.Q4

```[tasklist]
- [ ] Rename Modern.js Builder to **Rsbuild** and develop it as an independent brand
- [ ] Release the Modern.js DevTools
- [ ] Support for Storybook v7
- [ ] [Improve the JSON schema validation performance](https://github.com/web-infra-dev/modern.js/discussions/4706)
- [ ] [Improve the Modern.js benchmark](https://github.com/web-infra-dev/modern-js-benchmark)
- [ ] Provide deployment guidance
```

## 2023.Q3

```[tasklist]
- [x] [Rename Modern.js Doc to **Rspress** and develop it as an independent brand](https://github.com/web-infra-dev/rspress)
- [x] [Support for Modern.js data action](https://github.com/web-infra-dev/modern.js/pull/4736)
- [x] [Support for Rspack builtin:swc-loader](https://github.com/web-infra-dev/modern.js/discussions/4620)
- [x] [Support for building Vue 2 / Vue 3 applications](https://modernjs.dev/builder/en/guide/framework/vue3.html)
- [x] [Support for more intuitive Tailwind CSS configuration](https://github.com/web-infra-dev/modern.js/discussions/4509)
- [x] [Improve error printing and suggestions](https://github.com/web-infra-dev/modern.js/discussions/4325)
- [x] [Improve server performance](https://github.com/web-infra-dev/modern.js/pull/4632)
- [x] [Merge the libuild library to Modern.js Module](https://github.com/web-infra-dev/modern.js/discussions/4354)
```

### What does the proposed API look like?

1

**Comment by chenjiahan** [comment]
Outdated

**Comment by elisson-santos** [comment]
Outdated
